name: Deploying Config

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzc --delete --exclude="*.ts" --exclude=".git" --exclude="node_modules"
          path: ./
          remote_path: ${{ secrets.TARGET_DIR }}
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USER }}
          remote_key: ${{ secrets.SSH_KEY }}

      - name: Restart Configs
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: pm2 restart ${{ secrets.TARGET_DIR }}/${{ secrets.PM2_CONFIG }};